name = "dragonfly-operation-tools"
compatibility_date = "2026-08-01"
main = "src/worker.ts"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "dragonfly-ops-hub"
database_id = "70bdba60-3cbe-41a4-b29f-49357162469c"
